# Generated by Django 5.1.2 on 2024-11-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
