# Generated by Django 5.1.2 on 2024-11-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_delete_fooditem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffmember',
            table='staff_members',
        ),
    ]
